version: '2'
services:
  jenkins:
    build: .
    env_file:
        - env/java.env
        - env/jenkins.env
    privileged: true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - $PWD/jenkins-data:/var/jenkins_home
    ports:
     - "8080:8080"
     - "50000:50000"